// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzlitvvypesfvweyltgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6bGl0dnZ5cGVzZnZ3ZXlsdGd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNjI4MTksImV4cCI6MjA3MTkzODgxOX0.jl_yhQKRti8lBnVtwDYV1fAOjW3mf3jHSQRNvkhQgKQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});